image:
  repository: rancher/rancher-webhook
  tag: latest
  imagePullPolicy: IfNotPresent

global:
  cattle:
    systemDefaultRegistry: ""

preDelete:
  enabled: true
  image:
    repository: rancher/kubectl
    tag: v1.20.2
